[project]
name = "lwd-flask-pj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aws-sam-cli>=1.144.0",
    "boto3>=1.40.46",
    "flask>=3.1.2",
    "requests>=2.32.5",
]
